-- MySQL Script generated by MySQL Workbench
-- Wednesday 02 October 2019 11:48:10 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema graffiti
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema graffiti
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `graffiti` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `graffiti` ;

-- -----------------------------------------------------
-- Table `graffiti`.`_Migration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graffiti`.`_Migration` (
  `revision` INT(11) NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `datamodel` LONGTEXT NOT NULL,
  `status` TEXT NOT NULL,
  `applied` INT(11) NOT NULL,
  `rolled_back` INT(11) NOT NULL,
  `datamodel_steps` LONGTEXT NOT NULL,
  `database_migration` LONGTEXT NOT NULL,
  `errors` LONGTEXT NOT NULL,
  `started_at` DATETIME(3) NOT NULL,
  `finished_at` DATETIME(3) NULL DEFAULT NULL,
  PRIMARY KEY (`revision`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `graffiti`.`app`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graffiti`.`app` (
  `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `display_name` VARCHAR(45) NULL DEFAULT NULL,
  `mode` VARCHAR(20) NOT NULL DEFAULT 'carousal' COMMENT 'values -> carousel, tab, list',
  `hidden` TINYINT(4) NOT NULL DEFAULT 0,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `graffiti`.`dashboard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graffiti`.`dashboard` (
  `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `display_name` VARCHAR(100) NULL DEFAULT NULL,
  `icon` VARCHAR(45) NULL DEFAULT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `graffiti`.`app_dashboard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graffiti`.`app_dashboard` (
  `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `app_id` SMALLINT(5) UNSIGNED NOT NULL,
  `dashboard_id` SMALLINT(5) UNSIGNED NOT NULL,
  `user_id` VARCHAR(45) NOT NULL DEFAULT '-1',
  `order` SMALLINT(5) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Let order be multiples of 100 so that you can add new dashboards in between',
  `visible` TINYINT(4) NOT NULL DEFAULT 1,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `fk_app_has_dashboard_dashboard1_idx` (`dashboard_id` ASC) VISIBLE,
  INDEX `fk_app_has_dashboard_app_idx` (`app_id` ASC) VISIBLE,
  CONSTRAINT `fk_app_has_dashboard_app`
    FOREIGN KEY (`app_id`)
    REFERENCES `graffiti`.`app` (`id`),
  CONSTRAINT `fk_app_has_dashboard_dashboard1`
    FOREIGN KEY (`dashboard_id`)
    REFERENCES `graffiti`.`dashboard` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `graffiti`.`base_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graffiti`.`base_table` (
  `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `schema` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `graffiti`.`component`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graffiti`.`component` (
  `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `display_name` VARCHAR(100) NULL DEFAULT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `graffiti`.`query`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graffiti`.`query` (
  `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sql` LONGTEXT NOT NULL,
  `limit` VARCHAR(45) NULL DEFAULT NULL,
  `sort_by` VARCHAR(45) NULL DEFAULT NULL,
  `sort_type` TINYINT(4) NOT NULL DEFAULT 1 COMMENT '0 -> ASC\\\\n1 -> DESC',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `graffiti`.`chart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graffiti`.`chart` (
  `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `display_name` VARCHAR(45) NULL DEFAULT NULL,
  `component_id` SMALLINT(5) UNSIGNED NOT NULL,
  `query_id` SMALLINT(5) UNSIGNED NOT NULL,
  `help_text` VARCHAR(45) NULL DEFAULT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `fk_chart_query1_idx` (`query_id` ASC) VISIBLE,
  INDEX `fk_chart_component1_idx` (`component_id` ASC) VISIBLE,
  CONSTRAINT `fk_chart_component1`
    FOREIGN KEY (`component_id`)
    REFERENCES `graffiti`.`component` (`id`),
  CONSTRAINT `fk_chart_query1`
    FOREIGN KEY (`query_id`)
    REFERENCES `graffiti`.`query` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `graffiti`.`interaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graffiti`.`interaction` (
  `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `display_name` VARCHAR(100) NULL DEFAULT NULL,
  `type` VARCHAR(20) NULL DEFAULT NULL COMMENT '1. drilldown - chart_id\\\\n\\\\n2. drillout - take to a url',
  `tooltip` VARCHAR(200) NULL DEFAULT NULL,
  `drilldown_chart_id` SMALLINT(5) NULL DEFAULT NULL,
  `drillout_url` LONGTEXT NULL DEFAULT NULL COMMENT 'For url based drill outs. \\\\\\\\n\\\\\\\\nFormat= /application/:application_id',
  `send_query_params_in_url` TINYINT(4) NULL DEFAULT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `graffiti`.`chart_interaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graffiti`.`chart_interaction` (
  `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `chart_id` SMALLINT(5) UNSIGNED NOT NULL,
  `interaction_id` SMALLINT(5) UNSIGNED NOT NULL,
  `visible` TINYINT(4) NOT NULL DEFAULT 1,
  `order` SMALLINT(5) NOT NULL DEFAULT 1000,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `fk_chart_has_interaction_interaction1_idx` (`interaction_id` ASC) VISIBLE,
  INDEX `fk_chart_has_interaction_chart1_idx` (`chart_id` ASC) VISIBLE,
  CONSTRAINT `fk_chart_has_interaction_chart1`
    FOREIGN KEY (`chart_id`)
    REFERENCES `graffiti`.`chart` (`id`),
  CONSTRAINT `fk_chart_has_interaction_interaction1`
    FOREIGN KEY (`interaction_id`)
    REFERENCES `graffiti`.`interaction` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `graffiti`.`column`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graffiti`.`column` (
  `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `chart_id` SMALLINT(5) UNSIGNED NOT NULL,
  `name` VARCHAR(10) NOT NULL COMMENT 'Name of the column in chart table',
  `axis` VARCHAR(45) NOT NULL COMMENT 'x, y, z, ',
  `display_name` VARCHAR(45) NULL DEFAULT NULL,
  `unit` VARCHAR(45) NULL DEFAULT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `fk_axis_chart1_idx` (`chart_id` ASC) VISIBLE,
  CONSTRAINT `fk_axis_chart1`
    FOREIGN KEY (`chart_id`)
    REFERENCES `graffiti`.`chart` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `graffiti`.`comparison`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graffiti`.`comparison` (
  `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `graffiti`.`dashboard_chart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graffiti`.`dashboard_chart` (
  `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `dashboard_id` SMALLINT(5) UNSIGNED NOT NULL,
  `chart_id` SMALLINT(5) UNSIGNED NOT NULL,
  `user_id` VARCHAR(45) NOT NULL DEFAULT '-1',
  `order` SMALLINT(5) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Let order be multiples of 100 so that you can add new charts in between',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `layout_x` SMALLINT(5) NOT NULL DEFAULT 0,
  `layout_y` SMALLINT(5) NOT NULL DEFAULT 0,
  `layout_width` SMALLINT(5) NOT NULL DEFAULT 6,
  `layout_height` SMALLINT(5) NOT NULL DEFAULT 6,
  `visible` TINYINT(4) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_dashboard_has_chart_chart1_idx` (`chart_id` ASC) VISIBLE,
  INDEX `fk_dashboard_has_chart_dashboard1_idx` (`dashboard_id` ASC) VISIBLE,
  CONSTRAINT `fk_dashboard_has_chart_chart1`
    FOREIGN KEY (`chart_id`)
    REFERENCES `graffiti`.`chart` (`id`),
  CONSTRAINT `fk_dashboard_has_chart_dashboard1`
    FOREIGN KEY (`dashboard_id`)
    REFERENCES `graffiti`.`dashboard` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `graffiti`.`filter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graffiti`.`filter` (
  `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `display_name` VARCHAR(45) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `tooltip` VARCHAR(100) NULL DEFAULT NULL,
  `values_query` SMALLINT(5) UNSIGNED NULL DEFAULT NULL,
  `filter_query` SMALLINT(5) UNSIGNED NOT NULL COMMENT 'Subquery which will act as a filter',
  `parent_filter_id` VARCHAR(45) NULL DEFAULT NULL,
  `min` VARCHAR(45) NULL DEFAULT NULL COMMENT 'for date picker, slider etc',
  `max` VARCHAR(45) NULL DEFAULT NULL COMMENT 'for date picker, slider etc',
  `base_table_id` SMALLINT(5) UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `fk_filter_query3_idx` (`filter_query` ASC) VISIBLE,
  INDEX `fk_filter_base_table1_idx` (`base_table_id` ASC) VISIBLE,
  CONSTRAINT `fk_filter_base_table1`
    FOREIGN KEY (`base_table_id`)
    REFERENCES `graffiti`.`base_table` (`id`),
  CONSTRAINT `fk_filter_query3`
    FOREIGN KEY (`filter_query`)
    REFERENCES `graffiti`.`query` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `graffiti`.`dashboard_filter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graffiti`.`dashboard_filter` (
  `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `dashboard_id` SMALLINT(5) UNSIGNED NOT NULL,
  `filter_id` SMALLINT(5) UNSIGNED NOT NULL,
  `order` SMALLINT(5) NOT NULL DEFAULT 0,
  `visible` TINYINT(4) NOT NULL DEFAULT 1,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `fk_dashboard_has_filter_filter1_idx` (`filter_id` ASC) VISIBLE,
  INDEX `fk_dashboard_has_filter_dashboard1_idx` (`dashboard_id` ASC) VISIBLE,
  CONSTRAINT `fk_dashboard_has_filter_dashboard1`
    FOREIGN KEY (`dashboard_id`)
    REFERENCES `graffiti`.`dashboard` (`id`),
  CONSTRAINT `fk_dashboard_has_filter_filter1`
    FOREIGN KEY (`filter_id`)
    REFERENCES `graffiti`.`filter` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `graffiti`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graffiti`.`test` (
  `test` INT(11) NOT NULL,
  `test2` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`test`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
